#!/usr/bin/env bash
# This script displays "Best School" ten times and hi 
HOUR=0
while [ $HOUR -le 12 ]
do
MINUTE=1
while [ $MINUTE -le 59 ]
do
printf "%02d:%02d\n" $HOUR $MINUTE
MINUTE=$((MINUTE + 1))
done
HOUR=$((HOUR + 1))
done
