#!/usr/bin/env bash
#comment 
for pid_dir in /proc/[0-9]*
do
PID=$(basename "$pid_dir")
COMM_FILE="$pid_dir/comm"
if [ -f "$COMM_FILE" ]
then
COMM=$(cat "$COMM_FILE")
# Remove potential newline characters from the process name
COMM="${COMM%$'\n'}"
if [[ "$COMM" == *bash* ]]
then
echo "$PID $COMM"
fi
fi
done
